### ISSUE TITLE
Online usage

### ISSUE THREAD

**Issue by aleonnet** [ZhangRaymond/Neural-NILM#1]
Hi Zhang,
Nice job. Is there any article or website to followup and check the results of your approach?
Is this approach reliable to perform an online/real time appliance level energy disaggregation? 

I'm building a three phase smart meter that sends electrical parameters via MQTT to a Raspberry pi and would like to use it.

Thanks.

**Comment by ZhangRaymond** [comment]
Hi, Aleonnet,
thanks for your issue. A conference paper about this approach is on the way. Actually, from the perspective of application, the performance of DNN-based approaches in the existing researches is quite close. 
As for the real time disaggregation, I think Raspberry's computing power should cover this approach of such size. And I'm sorry that I haven't tested it on any mobile platform(including Raspberry pi). You can test it.  I'm also looking forward to your test.

Several related papers maybe useful for you: 

> Sequence-to-point learning with neural networks for nonintrusive load monitoring 

> Sliding Window Approach for Online Energy Disaggregation Using Artificial Neural Networks

> Neural Network Ensembles to Real-time Identification of Plug-level Appliance Measurements


Good Luck!

**Comment by aleonnet** [comment]
Hi @ZhangRaymond 
I'm trying to check some results. How do you generate pickle per house?

FileNotFoundError: [Errno 2] No such file or directory: 'data/house_2.pickle'

Thanks!

**Comment by ZhangRaymond** [comment]
Hi  Aleonnet,


Actually I lost my house_{}.pickle making code, but I remember this making code is very simple. I attached an inner structure image of house_{}.pickle for you and you can  rewrite the code by yourself.



Hint: the pickle data are dumped in sklearn.base.Bunch format.


[cid:89db98f9-7be9-445b-bb4e-bd42a9aee642]
________________________________
发件人: aleonnet <notifications@github.com>
发送时间: 2019年3月18日 10:38
收件人: ZhangRaymond/Neural-NILM
抄送: Raymond, Zhang Yuanmeng; Mention
主题: Re: [ZhangRaymond/Neural-NILM] Online usage (#1)


Hi @ZhangRaymond<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZhangRaymond&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=pyqlpPMznuG7RTx02BfBcw&m=pNwf1wl9Xk9I_v5rMeb95cmVynzR7m6JbA9SEfQ5ZjA&s=i1WP-8SpYEjxAsLk-Gyinmx6d2YfSlLDddgaqvbz9z4&e=>
I'm trying to check some results. How do you generate pickle per house?

FileNotFoundError: [Errno 2] No such file or directory: 'data/house_2.pickle'

Thanks!

―

**Comment by aleonnet** [comment]
Hi Zhang,
What do you mean by "I attached an inner structure image of house_{}.pickle for you"?
There's nothing attached...

**Comment by ZhangRaymond** [comment]
> Hi Zhang,
> What do you mean by "I attached an inner structure image of house_{}.pickle for you"?
> There's nothing attached...

**Comment by ZhangRaymond** [comment]
![a](https://user-images.githubusercontent.com/16101490/54924826-1cbe8b80-4f48-11e9-8df6-d7f4946ec4f7.png)

Hi, Aleonnet,
I replied you on an e-mail client, not on github, maybe you can not see the attached image on github.
Here you can have a try.
